name: flutter_application_1
description: "A Flutter note scrolling application with tagging and random viewing."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  grouped_list: ^5.1.2  # Add this line
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Local database
  sqflite: ^2.3.3
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Image handling
  image_picker: ^1.1.2
  image: ^4.2.0
  
  # Firebase (keeping your existing dependencies)
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
