// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_A0yZBtH020N528f1u3q5MvJqLomJoY',
    appId: '1:17724130023:web:74c2f7c87e7ee20bb09842',
    messagingSenderId: '17724130023',
    projectId: 'my-revision-app-b8268',
    authDomain: 'my-revision-app-b8268.firebaseapp.com',
    storageBucket: 'my-revision-app-b8268.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcYfJ6oPferc3cvi0gEypvdM16qnV0b6w',
    appId: '1:17724130023:android:8aeddd38a36d700fb09842',
    messagingSenderId: '17724130023',
    projectId: 'my-revision-app-b8268',
    storageBucket: 'my-revision-app-b8268.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzf3sNFjStk-B8Ifr3DFufpBmamfX7cGA',
    appId: '1:17724130023:ios:5627c841368fdd57b09842',
    messagingSenderId: '17724130023',
    projectId: 'my-revision-app-b8268',
    storageBucket: 'my-revision-app-b8268.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzf3sNFjStk-B8Ifr3DFufpBmamfX7cGA',
    appId: '1:17724130023:ios:5627c841368fdd57b09842',
    messagingSenderId: '17724130023',
    projectId: 'my-revision-app-b8268',
    storageBucket: 'my-revision-app-b8268.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw_A0yZBtH020N528f1u3q5MvJqLomJoY',
    appId: '1:17724130023:web:28c71cdcb5769de5b09842',
    messagingSenderId: '17724130023',
    projectId: 'my-revision-app-b8268',
    authDomain: 'my-revision-app-b8268.firebaseapp.com',
    storageBucket: 'my-revision-app-b8268.firebasestorage.app',
  );
}
